### ISSUE TITLE
Email regex incorrectly matches on pipe literal.

### ISSUE THREAD

**Issue by rcocks** [alphagov/notifications-admin#1369]
Hello,

Your email regex for validating domains matches the domain preceded by an `@`, a full-stop `.` or (mistakenly I believe) the pipe character, `|`.

When evaluated, the following code prints "true".

```
import re
email_regex = (r"[\.|@]({})$".format("|".join(["gov.uk","mod.uk"])))
print bool(re.search(email_regex, "richard.cocks@example.com|gov.uk"))
```

That code is the code from app/utils.py lines 258,259 with the allowed domains list expanded with the examples here and an email address filled in.

I don't know how the pipe character would be handled in the case of trying to email `richard.cocks@example.com|gov.uk`, or whether it would get through other validation but could lead to potential vulnerability if for example the pipe and anything after it were to be discarded.

I believe the regex intended was `r"(?:[\.]|[@])({})$".format(...)` which matches one of `@` or `.` followed by an allowed domain. (with a non-capturing group here to preserve the previous group numbers although they aren't used anyway).

**Comment by quis** [comment]
Hey @rcocks,

Thanks for taking the time to report this.

The code you’re talking about is just for checking whether an email address is a government domain. 

We do a separate check beforehand to see if any email address is ‘valid’. This separate check will catch anything like `test@example.com|gov.uk`, so you’d never be able to register a Notify account with that address:
![image](https://user-images.githubusercontent.com/355079/28261734-5684b11a-6ad8-11e7-9ba1-601e8cc7b5a1.png)

The code that’s validating the email address can be found here: https://github.com/alphagov/notifications-utils/blob/2e1cac5e24b59f3f90cc2aad17e16728dbf19950/notifications_utils/recipients.py#L480-L512

I’ve added a test to make sure we don’t regress: https://github.com/alphagov/notifications-utils/pull/183

**Comment by rcocks** [comment]
I was aware there was different code to validate addresses which is why I mentioned not testing that. The allowed domain detection is still using an incorrect regex though isn't it? The added test stops it being elevated to a serious issue but why not fix the domain detection regex also?

**Comment by quis** [comment]
Dealing with email addresses is [hard](https://fightingforalostcause.net/content/misc/2006/compare-email-regex.php). A good approach to dealing with hard problems is breaking them up. That’s the decision we’ve made here:
- one part of the code checks their validity
- one part checks whether the domain or top level domain is in our whitelist

This means that the regex which checks the domain assumes it’s being given a valid email address. Which, as you point out, could lead to a developer introducing a vulnerability without realising.

But trying to craft one regex which checks both things would be really hard. Your suggested regex successfully rejects `test@example.com|gov.uk`. But it doesn’t catch `test@example.com|example.gov.uk`, which has the same issue, or `test@example.com,test@example.gov.uk`.

Another good reason for breaking them up into two separate checks is that we can reuse the code that checks for an email address’s validity on non-government email addresses, which we couldn’t do if it was one big regex.

Pull requests welcome if you think there’s a better way though…
