### ISSUE TITLE
Copying API key to clipboard puts a space on either end

### ISSUE THREAD

**Issue by Floppy** [alphagov/notifications-admin#4216]
As title; extra spaces when copying API keys! This stops them working when pasted, obviously :)

1. Create an API key
2. Copy said API key to clipboard using the button
3. Paste API key somewhere else, observe leading and trailing spaces

**Comment by Floppy** [comment]
Also, copying a template ID seems to leave a trailing space on that, too.

**Comment by quis** [comment]
Hey @Floppy, thanks for raising this. Can you let us know which browser(s) and operating system(s) you’ve seen the problem in?

**Comment by Floppy** [comment]
Sure thing, should have thought of that already! 

* Firefox 99
* MacOS 12.3.1

I know that @gweaton has also had this problem, not sure of their browser specifics though.

**Comment by quis** [comment]
Hi again @Floppy, just to let you know this should be fixed now. Thanks again for taking the time to raise the issue.

**Comment by Floppy** [comment]
No worries! Thanks for fixing it!
